### ISSUE TITLE
Secure context for EditContext?

### ISSUE THREAD

**Issue by snianu** [w3c/edit-context#11]
Should EditContext be only allowed in a secure context?

**Comment by annevk** [comment]
That seems like a good idea.

**Comment by dandclark** [comment]
@snianu , @annevk  could you elaborate a bit more on why you think EditContext would need to be SecureContext-only? Seems to me like EditContext isn't much more powerful from a security standpoint than normal editing APIs/events. It can intercept keystrokes, editing actions, etc. but normal event listeners can already get that kind of stuff.

**Comment by snianu** [comment]
@dandclark I don't have a strong opinion on whether or not EditContext should only be accessible in a secure context, so I'm fine with either. I agree with you that the information that EditContext stores is already accessible via editing events and other DOM APIs. However, in EditContext, we also store the plain text representation of the editable element context which is now accessible to malicious authors using a single command (editContext.text), so EditContext just makes it easier to find content compared to event listeners where the author has to find the editable element context (which is usually the focused element so I'm not sure in what cases it would be different), and then walk through the DOM to actually get the plain text representation of the content in the DOM for that editable element context.

**Comment by dandclark** [comment]
This seems relevant to guiding the decision: https://w3c.github.io/webappsec-secure-contexts/#threat-risks

IMO EditContext does not rise to the same level of risk as the features mentioned in that section. The editable text would be in the DOM anyway for a non-EditContext editor. And while EditContext can see composition events, it doesn't have direct access to input devices.

**Comment by dandclark** [comment]
We discussed this in the TPAC Editing WG meeting and resolved that SecureContext is not needed for EditContext.
> Dan: Should it only work in SecureContext. In issue I have added link to cases when secure context is used - normally when you give access to more data. That is not the case with EditContext. You get access to the same kind of information. Yes, bullet one applies, you do get access to “confidential data” the user types in, but the same is true for contenteditable. I would not limit it, but I am open to other ideas.
Johannes: What about an intranet site that only uses ip numbers, no certificates?
Dan: I don’t think that would not work if we require secure context.
Ryosuke: We don’t see need for secure context.
Johannes: How about Mozilla?
Edgar: I don’t see need for secure context, will bring it up with Masayuki
RESOLUTION: No need for SecureContet for EditContext. Will revisit in case of new arguments from Mozilla.
