### ISSUE TITLE
EditContext: If nested elements attached by `EditContext`, what happens?

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/edit-context#13]
If there are 2 or more elements attached by `EditContext`, one can be a descendent of another. In my understanding, only most ancestor one can have focus, so `EditContext` of descendents do not work?

**Comment by alexkeng** [comment]
That's correct. EditContext is activated (which means getting user text input) only when the associated element is focused, so in your case the EditContext of descendants will never be activated.

**Comment by dandclark** [comment]
We dug into this question pretty thoroughly in https://github.com/w3c/edit-context/issues/53, and I think the behavior defined there should be sufficient. I'll close this issue, but please feel free to reopen if there's anything we overlooked.
