### ISSUE TITLE
EditContext: "is activated" is not defined

### ISSUE THREAD

**Issue by annevk** [w3c/edit-context#20]
Should this be defined in terms of DOM's activation behavior? Something else?

**Comment by dandclark** [comment]
I don’t think the HTML spec’s concept of activation behavior maps well to EditContext. While HTML’s activation behavior describes an action that can happens while processing an event, an EditContext’s concept of “active” is a boolean state; an EditContext can either be active or not. In the newer spec that’s defined [here](https://w3c.github.io/edit-context/#dfn-active-editcontext:~:text=An%20EditContext%20is%20active%20when%20its%20associated%20element%2C%20or%20a%20descendant%20of%20its%20associated%20element%2C%20for%20which%20it%20is%20an%20editing%20host%2C%20is%20focused.) as follows:
“A user agent should have at most one active`EditContext`. An `EditContext` is active when its associated element, or a descendant of its associated element, for which it is an [editing host](https://html.spec.whatwg.org/multipage/interaction.html#editing-host), is [focused](https://html.spec.whatwg.org/multipage/interaction.html#focused).”

Let me know if that looks good to you. We could consider a different keyword if you think there’s too much overlap with the concept of activation behavior.

**Comment by annevk** [comment]
That sentence makes it sound like the `EditContext` is the editing host, but in #21 you said the element is.

**Comment by dandclark** [comment]
You're right, this sentence seems off. I think the intent here was to say "or a descendant of its associated element, for which *the associated element* is an [editing host](https://html.spec.whatwg.org/multipage/interaction.html#editing-host), is [focused](https://html.spec.whatwg.org/multipage/interaction.html#focused).”

But I think it's clearer to just delete that part: https://github.com/w3c/edit-context/pull/37

**Comment by dandclark** [comment]
This should all be clearer in the spec now.
A document has an [active EditContext](https://w3c.github.io/edit-context/#dfn-active-editcontext), which is determined via the steps in [Determine the Active EditContext](https://w3c.github.io/edit-context/#determine-the-active-editcontext), which happens as part of [Update the Text Edit Context](https://w3c.github.io/edit-context/#update-the-text-edit-context), which should get patched in as part of the event loop as described in https://w3c.github.io/edit-context/#event-loop-changes.

An EditContext's associated element (not the EditContext itself) becomes an editing host: https://w3c.github.io/edit-context/#dfn-editcontext-editing-host
