### ISSUE TITLE
EditContext: define internal model

### ISSUE THREAD

**Issue by annevk** [w3c/edit-context#22]
Currently `EditContext` objects seem to be manipulated by the standard through its public IDL members. That cannot be implemented in that manner and therefore it shouldn't be defined as such. Instead you should define the private fields/internal slots/associated concepts of `EditContext` objects and manipulate those. And the various getters can return them.

**Comment by dandclark** [comment]
This is addressed in the [updated spec draft](https://w3c.github.io/edit-context); all the pieces of `EditContext` state are now defined and used separately from their pubic IDL members.

I'll close out this issue, but please let me know if looks like we missed any.

**Comment by annevk** [comment]
Overall this looks like a substantial improvement, thanks.

The next step would be to review all the entry points are clear and the state is only modified at appropriate points in time. I'll file a separate issue on something I spotted while quickly scanning things.
