### ISSUE TITLE
EditContext: processing model

### ISSUE THREAD

**Issue by annevk** [w3c/edit-context#23]
The larger issue with this specification I wanted to raise is two-fold:

1. It's very much unclear how this integrates with the larger web platform processing model. w3c/edit-context#20 and w3c/edit-context#21 touch upon this. How does this change the model of elements and focusing? What user input actions end up redirected here vs the element?
2. The processing model of the `EditContext` object itself is unclear. w3c/edit-context#22 touches upon this. For instance, at some point the draft says "Update the text, selectionStart, selectionEnd, compositionRangeStart, compositionRangeEnd, and isInComposition properties of the activated EditContext." but it doesn't actually say what any of these values are supposed to be set to and what that depends upon.

**Comment by alexkeng** [comment]
We appreciate the feedback and agree that more clarity is needed. We'll address related issues and add more details in the next revision

**Comment by dandclark** [comment]
We've made a lot of changes that I think address the issues raised here. See the sub-issues linked from this issue for specific fixes.

See also https://github.com/w3c/input-events/pull/145 which we're not going to land until EditContext is shipping/close to shipping. That PR defines the entry point for user input.

I'm going to close this out -- given the amount of churn that's happened relevant to this issue it's probably best to start with a new issue if there's anything that still needs improvement.
