### ISSUE TITLE
inputMode property of EditContext

### ISSUE THREAD

**Issue by travisleithead** [w3c/edit-context#3]
Issue transferred from https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/88

@snianu opened the issue on 2019-08-28

inputMode property on the EditContext denotes what type of input the EditContext is associated with. This information is typically provided to the underlying system as a hint for which software keyboard to load (e.g. keyboard for phone numbers may be a numpad instead of the default keyboard). This defaults to 'text'.

This is very similar to the inputMode (https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-inputmode-attribute) attribute in textarea/contenteditable elements. One value that is missing from the inputMode attribute list of supported values is "**password**".

On Windows (and I believe Android/iOS VKs too), the software input panel provides a different layout for password. The text input service doesn't perform any text input intelligence such as auto-capitalization, suggestions on the VK etc. 

I've added screenshots of various input panels to show the differences in [this ](https://github.com/MicrosoftEdge/MSEdgeExplainers/pull/87)PR

We definitely want to support password on EditContext.

Questions:
1. Should we add this property to the list of supported inputMode attribute values? 
2. The spec for inputMode (the attribute) says to fallback to the default VK if the attribute specified is unsupported.  Does it make more sense though to fallback from something like numeric to decimal or vice versa?

---

@mustaqahmed commented on 2019-08-30

> Regarding adding `inputmode="password"` to the HTML spec: I verified that the VK for passwords on Android is also different, so it makes sense to update the HTML spec.  Just filed https://github.com/whatwg/html/issues/4875 to discuss the change on HTML-side.

@travisleithead commented on 2020-02-12

> @snianu @gked noted that adding `inputmode` would be a great addition. Regarding your 2nd question, we'd rather not see divergent behavior from the HTML spec's definition. If there is a larger concern there, then it can be raised with HTML. Would you mind making an update to the explainer?

**Comment by dandclark** [comment]
The more recent thinking on this after discussing with @snianu and @alexkeng is that we don't need `inputMode` to be directly settable on EditContext, but can instead have EditContext use the `inputMode` of the element in the DOM that the user is currently editing. Since `inputMode` is a global attribute this even works for `<canvas>`.

This is simpler overall as there will be no confusion in cases where the `inputMode` on the EditContext and the `inputMode` in the DOM conflict.

Hence, closing.
