### ISSUE TITLE
The `compositionend` event is no longer fired

### ISSUE THREAD

**Issue by tidoust** [w3c/edit-context#34]
EditContext defines the `oncompositionend` `EventHandler` attribute for the `compositionend` event (the event itself is defined in [UI Events](https://w3c.github.io/uievents/#compositionend)). However, as opposed to `compositionstart`, recent updates to the spec mean that the `compositionend` event is no longer fired by algorithms in the spec. Shouldn't it? Or is firing supposed to be handled by the UI Events spec?

**Comment by dandclark** [comment]
Yes, this spec should be firing `compositionend`. This is fixed now with https://github.com/w3c/edit-context/pull/62.
