### ISSUE TITLE
Should it be required to call updateCharacterBounds() synchronously in the characterboundsupdate event handler?

### ISSUE THREAD

**Issue by dandclark** [w3c/edit-context#36]
In the examples in the spec draft, [updateCharacterBounds](https://w3c.github.io/edit-context/#ref-for-dom-editcontext-updatecharacterbounds-1) is called synchronously inside the [characterboundsupdate](https://w3c.github.io/edit-context/#dom-characterboundsupdateevent) event handler. However, in conversations with Adobe they've shared that they would like to be able to call it asynchronously, outside of the event handler. This is because the design they would like to follow involves a worker performing text layout, so the text bounds are not available synchronously.

On Windows this should generally be OK because the browser can call [`ITextStoreACPSink::OnLayoutChange`](https://learn.microsoft.com/en-us/windows/win32/api/textstor/nf-textstor-itextstoreacpsink-onlayoutchange) at any time, and TSF will call back into the browser, get the updated character bounds position, and redraw the IME window. The worst case is that the user might see the window change positions after the update comes from the author script.

On Mac, we've observed that even after calling [`NSTextInputContext.invalidateCharacterCoordinates`](https://developer.apple.com/documentation/appkit/nstextinputcontext/1535165-invalidatecharactercoordinates?language=objc), the IME window will not be repositioned until the user starts a new composition. So if the author takes too long to call `updateCharacterBounds`, there's a risk that the IME window would be drawn in the wrong place, without updated bounds, and there would be no way to reposition it without restarting the composition. See https://openradar.appspot.com/FB8936158; it's not clear if this is by-design or is something that could be changed so that the window position updates dynamically.

I should also mention that due to the architectures of modern browsers there will likely need to be asynchronous IPC between the browser process where OS text input services hook in, and the render processes hosting author JavaScript. So it's probably hard to guarantee that all these operations happen synchronously with respect to the OS. It's more a matter of timing, where delayed author script would make it more likely that bounds are not yet available when the OS text input service asks for them.

In my opinion we should allow these bounds updates to happen asynchronously to give the maximum amount of flexibility to web devs, and because of the general difficulty of ensuring that the OS text input service sees things everything synchronously due to modern browser architecture. But I'd like to learn if there are problems here I might not be aware of, particularly if anyone is more familiar with IME window positioning on Mac OS.

cc folks who might be interested: @alexkeng @snianu @chrishtr @annevk

**Comment by chrishtr** [comment]
cc @masayuki-nakano also

**Comment by masayuki-nakano** [comment]
> On Windows this should generally be OK because the browser can call [`ITextStoreACPSink::OnLayoutChange`](https://learn.microsoft.com/en-us/windows/win32/api/textstor/nf-textstor-itextstoreacpsink-onlayoutchange) at any time, and TSF will call back into the browser, get the updated character bounds position, and redraw the IME window. The worst case is that the user might see the window change positions after the update comes from the author script.

I think so, and the worst case should be handled by the browsers. Gecko/Firefox notify TSF of window position change with `ITextStoreACPSink::OnLayoutChange`. Traditionally, IMM API can update the position anytime. Therefore, this should work as expected with most IMEs.

> On Mac, we've observed that even after calling [`NSTextInputContext.invalidateCharacterCoordinates`](https://developer.apple.com/documentation/appkit/nstextinputcontext/1535165-invalidatecharactercoordinates?language=objc), the IME window will not be repositioned until the user starts a new composition. So if the author takes too long to call `updateCharacterBounds`, there's a risk that the IME window would be drawn in the wrong place, without updated bounds, and there would be no way to reposition it without restarting the composition. See https://openradar.appspot.com/FB8936158; it's not clear if this is by-design or is something that could be changed so that the window position updates dynamically.

When I tried to update it for window position/size changes on macOS, I also failed to do it with the API. Even if Apple fixed the issue if it's a bug of macOS, some IMEs may have not implemented it yet since there is no way to test the handler.

And also about Linux, Gecko/Firefox uses GTK/GDK. They have similar API to IMM on Windows. Therefore, it's fine to update the position anytime.

> In my opinion we should allow these bounds updates to happen asynchronously to give the maximum amount of flexibility to web devs, and because of the general difficulty of ensuring that the OS text input service sees things everything synchronously due to modern browser architecture. But I'd like to learn if there are problems here I might not be aware of, particularly if anyone is more familiar with IME window positioning on Mac OS.

If `[NSTextInputClient firstRectForCharacterRange:actualRange:]` is called in same event loop as keydown, it's impossible to wait for an update from web apps. On the other hand, currently, Gecko caches character rects around caret before starting composition and updates the cache when content process notifies the parent process of finishing layout, and uses the cache to reply to the query. This approach does not return the latest layout information to IME, but (as far as I know) this works with any IME properly. Therefore, the latest character rect updates may not be required for IME unless web apps change the text style frequently.

**Comment by dandclark** [comment]
In today's EditingWG meeting, we resolved to allow these character bounds updates to be async. Apple folks are going to take a look at the Mac bug where the IME window position doesn't update.

We should probably have a note in the spec that this is explicitly allowed. Leaving this Issue open to track me adding that.

Here are the notes:
> [08:44] <whsieh> https://github.com/w3c/edit-context/issues/36
[08:45] <whsieh> dandclark: EC — authors can supply geometry for where active composition, etc. are
[08:46] <whsieh> dandclark: authors are expected to call updateCharacterBounds in characterboundsupdate event
[08:46] <whsieh> dandclark: ambiguous — when is the author supposed to call that?
[08:46] <whsieh> dandclark: feedback from adobe — they want to do the layout asynchronously
[08:46] <whsieh> dandclark: works fine on windows using TSF
[08:47] <whsieh> dandclark: on macOS, -[NSTextInputContext invalidateCharacterCoordinates] seems to be broken — IME window does not redraw until composition ends
[08:48] <whsieh> dandclark: filed https://openradar.appspot.com/FB8936158 (rdar://72204786)
[08:48] <whsieh> dandclark: we may not be able to implement it properly on macOS
[08:49] <whsieh> dandclark: want to resolve — triggering async is okay
[08:49] <whsieh> dandclark: robust w.r.t. async/multiprocess archtectures
[08:51] <whsieh> dandclark: reduced repro — in any app on macOS, starting a composition in IME and scrolling
[08:51] <whsieh> chris: https://bugs.chromium.org/p/chromium/issues/detail?id=1151301
[08:55] <whsieh> dandclark: TSF also doesn't know about scrolling
[08:56] <whsieh> chris: invalidateCharacterCoordinates does not seem to do anything
[08:58] <whsieh> whsieh: yeah let's resolve on async for now
[08:58] <whsieh> snianu: https://chromium-review.googlesource.com/c/chromium/src/+/2586189
