### ISSUE TITLE
What happens when an editing host is associated with an EditContext?

### ISSUE THREAD

**Issue by dandclark** [w3c/edit-context#38]
What should happen if an EditContext is associated with an element that is already editable (from `contenteditable`, or a child of an element that is `contenteditable`, or anything in a `designMode` document)?

(We currently exclude elements that are "inherently" editable like `<textarea>` per the [supported elements ](https://w3c.github.io/edit-context/#supported-elements) list.)

The option I am leaning towards is that the EditContext behavior would override any existing editable behavior. That is, things would work as if the associated element had not already been editable.

@snianu @alexkeng has this been considered already?

Thanks @annevk for pointing this out in https://github.com/w3c/edit-context/issues/21#issuecomment-1539621278

**Comment by johanneswilm** [comment]
@dandclark We discussed earlier that it should be possible to combine `contenteditable` with `EditContext`. The reason one would want to do this is that one would use the `contenteditable` element to move the caret with arrow keys (especially in the block direction), etc. . One may also want to catch the `beforeinput` events for certain input.

However, I am wondering it would be possible to switch back and forth between the two - to switch between `contenteditable` and `EditContext` whenever a composition is about to start or end (`compositionstart` event). If it's possible to switch like that, then I guess it wouldn't be a problem if the `contenteditable` stops working while `EditContext` is in use.

**Comment by johanneswilm** [comment]
Hey again @dandclark thanks to your help offline, I was able to do some basic testing. As far as I can gather, `EditContext` when associated with an HTML is supposed to draw the caret and also move it with the arrow keys, correct? If that is the case, then I don't see the need for having an element be both contenteditable and EditContext at the same time. So I'd say the EditContext overrides the contenteditable should be fine.

I've noted though that the caret drawing and arrow movement only seems to work if there are no sub elements [1]. It does not work with sub elements [2]. Another concern is that it seems like only beforeinput events related to character input are triggered, not those related to paragraph splitting, format changes, or deletion [2]. If that is how it is supposed to work, it would seem like a show stopped.

[1] https://htmlpreview.github.io/?https://github.com/w3c/edit-context/blob/gh-pages/native_selection_demo.html

[2] https://johanneswilm.github.io/editContext-test/

**Comment by dandclark** [comment]
Thanks @johanneswilm for taking a look!

> `EditContext` when associated with an HTML is supposed to draw the caret and also move it with the arrow keys, correct?

That's right. Agreed there's not a need for an element to be both contenteditable and EditContext. When opening the issue I wasn't sure which one should "win" if both are set on an element. Seems that EditContext overriding the contenteditable is a good choice.

Regarding the issues with sub-elements, you're hitting a bug in the Chromium implementation where child elements of an EditContext do not automatically become editable. I have a fix at https://chromium-review.googlesource.com/c/chromium/src/+/4642263 which I will try to land ASAP. Once fixed, caret navigation should work normally and the EditContext element should receive `beforeinput` for paragraph splitting, formatting changes, etc.

In the meantime, a workaround is to place `contenteditable=""` on any child elements, at which point per the behavior suggested in #53 they will start to act like part of the EditContext. I confirmed that this works as expected in your test page.

**Comment by johanneswilm** [comment]
@dandclark How about the length of the editable text? Are there any restrictions on how much text can be loaded into the `EditContext` and are those restrictions different from `contenteditable`? If the restrictions differ, then maybe there could be an argument for needing a combination of the two.

**Comment by dandclark** [comment]
I don't think there's any length restrictions imposed by the spec.

**Comment by johanneswilm** [comment]
@dandclark Ok, and how about in practice in the only implementation that exists so far? I understand that there is a limit to the amount of text that is put into the buffer for the IME to work with (understand the context of the composition). Is the amount of text in that buffer not in any way related to how much the `EditContext` can handle?

**Comment by dandclark** [comment]
I think any limit on the amount of text that can be sent to the IME would be the same whether that text were being edited is in an EditContext or a contenteditable.

For the limit of the EditContext itself, in Chromium it would be the max size of the [String](https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:third_party/blink/renderer/platform/wtf/text/wtf_string.h) class. If that limit turned out to be an issue in practice, any implementation should be able to make changes to hold an EditContext buffer of arbitrary size (until heap memory runs out). So I don't it needs to be a factor in decisions about the spec is shaped.

**Comment by dandclark** [comment]
Notes from 10/8/2023 EditingWG discussion: 

> 6:07 PM dandclark: What happens when an editing host is associated with an EditContext?
6:07 PM which one should win?
6:08 PM <smaug> smaug: I agree that EditContext should win
6:10 PM johanneswilm: I did some testing. If you associate an EditContext with editing host, you do get all the input events
6:12 PM smaug: so you get input events in both places. But how do you handle them
6:12 PM johanneswilm: you'd handle formatting events in editing host
6:15 PM dandclark: for just typing editing host gets all the events and EditContext events too
6:17 PM smaug: so is the DOM modified when user types?
6:18 PM wenson: maybe this is similar to some other cases when beforeinput event is fired but there is no dom modification
6:19 PM smaug: ok, so it is only beforeinput event which is dispatched
6:20 PM <whsieh> present+
6:21 PM <smaug> resolution: EditContext wins, also editing host gets beforeinput

I'll make a change to the spec to clarify this.

**Comment by dandclark** [comment]
Updated the spec to reflect the resolution: https://github.com/w3c/edit-context/pull/56
