### ISSUE TITLE
Custom spellchecking

### ISSUE THREAD

**Issue by travisleithead** [w3c/edit-context#5]
This issue was migrated from https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/119

@Reinmar opened this issue on 2019-09-19

I agree to everything that's currently in the explainer:

> Web apps have no way today to integrate with spellcheck from the browser except through editable elements. Using the EditContext will make the native spellchecking capabilities of the browser unreachable. There is demand for an independent spellchecking API.
>
> For web apps or editing frameworks relying on editable elements to provide this behavior, it may be a barrier to adoption of the EditContext. Note, however, there are heavily used web editing experiences (Office Online apps, Google docs) that have replaced spell checking with a custom solution who will not be blocked from adopting a better text input integration story, even in the absence of a separate spellcheck API. Similarly, there are also editing experiences, e.g. Monaco, that don't use spell checking from the browser because an element like a contenteditable won't understand what's a string and what's a class name leading to a lot of extra innappropriate squiggles in the code editing experience.

I confirm that this would be a barrier for us, right now. 

There are two options regarding custom spellchecking:

* client-based spellchecking,
* server-based spellchecking.

The former requires downloading quite heavy dictionaries to the client and then affects the site performance, battery drainage, etc. Also, if you'd like to have automatic detection, it becomes even trickier (and heavier). But the size aspect will be a barrier here for many developers. EN_US dictionary is 190KB, AFAICS. That's a lot.

The performance aspect may be a barrier too. I remember Slack having to disable its spellchecking because of this. I'm not sure what was the problem there, but it's certainly something to take into consideration.

Server-based spellchecking, on the other hand, can be much more powerful, but it's no go for component authors. Imagine you're building a JS-based RTE. You can now enable it in your app by a simple script tag + 1LOC. If server-side was needed, it'd require incomparably more effort to set up.

Therefore, some browser API would be a must here, if we consider adoption of EditContext API beyond apps like Google Docs and Office Online.

---

@gked commented on 2019-10-07

> Thanks, @Reinmar. great points. Currently working on Spellchecker API explainer. Looking to share it publicly, in a few weeks.

[editor's note: there is still an unpublished spellchecker API explainer waiting to be published]

**Comment by dandclark** [comment]
That text from the explainer is actually no longer true. EditContext can integrate with the native spellchecker by listening for `beforeinput` type `"insertReplacementText"`. See [this example](https://w3c.github.io/edit-context/#example-how-beforeinput-can-be-used-to-catch-insertreplacementtext-to-apply-spelling-changes) in the spec.

The exception is when `<canvas>` is used to implement the editor view.
