### ISSUE TITLE
Event firing and editability for nested editable elements

### ISSUE THREAD

**Issue by dandclark** [w3c/edit-context#53]
There are some interesting cases to consider for nested editable elements that I haven't seen discussed anywhere.

The following example includes the cases that I think are important to look at. Throughout the example the text inside each node indicates where events should be targeted when the user edits in that node. Assume that every element with `id="edit-context-*"` is associated with its own instance of EditContext.

```html
  <div id="edit-context-0">Text in EditContext-associated element, should be editable
    <div id="default">
      Element child of EditContext, should be editable <!-- Currently not editable in Chromium implementation -->
    </div>
    <div id="noteditable" contenteditable="false">
      Marked contentEditable="false", should not be editable
      <div id="editable-in-noteditable" contenteditable="">
        This is a contenteditable="" child of contenteditable="false" parent.
        This node should be editable. It should be the target of beforeinput/input events when the user edits here.
        The grandparent node #edit-context-0 should not be the target of beforeinput/input events,
        and the EditContext should not receive
        textupdate events
        <div id="edit-context-2">
          This is an EditContext child of a contenteditable="". Since this is the child of an editable element, when the user
          types here, it's the parent contenteditable="" gets input/beforeinput events,
          and this doesn't. Basically the EditContext association is a no-op.
        </div>
      </div>
      <div id="edit-context-3">
        This is an EditContext child of contenteditable="false" parent.
        This node should be editable, and this EditContext (but not the
        grandparent EditContext) should get events, since there is an
        intermediate non-editable parent.
      </div>
    </div>
    <div id="editable-in-ec" contenteditable="">
      This is a contenteditable="" child of EditContext.
      It inherits editability from the parent and it should not be the target of beforeinput/input events.
      Setting contenteditable="" on this node is basically a no-op.
    </div>
    <input id="input" value="Input in EditContext. Events are fired against this element, and not against any parent EditContext.">
    <div id="edit-context-4">
      EditContext child of EditContext. When user types here,
      events are fired only against the parent EditContext, not this one.
      Since the parent element was editable, the EditContext association is basically a no-op.
    </div>
  </div>
```

Here is a live demo page for this example; open the console to see the events that are fired: https://gold-dirt-chickadee.glitch.me/

Note that "editability" means slightly different things for elements that become editable via EditContext via ContentEditable; I've attempted to cover the differences here: https://w3c.github.io/edit-context/#edit-context-differences.

These behaviors are what I've observed to happen with `contenteditable` in browsers today, and I'm attempting to just extend it to EditContext. If the details of event firing in these nested scenarios are captured in any spec, I couldn't find it. The behavior could be summarized as:
- Child nodes inherit editability from their parents, unless they are explicitly marked `contenteditable="false". This happens transitively, i.e. the grandparent nodes will also be editable unless marked otherwise, etc.
- Setting editability on a node that has already inherited editability from its parent is a no-op with respect to how befireinput/input/textupdate events are fired. It is still the parent that will be the target of these events when users perform editing actions in the child node.

Does this seem right?

**Comment by johanneswilm** [comment]
The point of having contenteditable=false inside of content-editable true, and maybe even a like on an island, has been to prevent the browser from making unwanted DOM changes in certain places. 

In the case of EditContext, where the JavaScript gets to decide which input to react upon and which ones to ignore, I am thinking this is probably not much of an issue. So therefore it will be fine either way. Note though https://github.com/w3c/edit-context/issues/38#issuecomment-1634069276 .

**Comment by dandclark** [comment]
Good point, agreed that `contenteditable=false` is not strictly needed to work for EditContext.

I think it's nice to have it work this way though because it will be easier to understand for authors (and implementers) who are already familiar with `contenteditable`. A goal of the approach above is, to the extent possible, make EditContext work the same way as `contenteditable`, so letting `contenteditable=false` still prevent editability fits with that approach.

**Comment by johanneswilm** [comment]
I agree, it makes sense to make it behave like `contenteditable` as much as possible so that it's easier to deal with for all those familiar with `contenteditable`, even if there will be less interest in doing this because it's not required to the same degree.

**Comment by dandclark** [comment]
Notes from 10/8/2023 EditingWG discussion:

> 6:22 PM "Event firing and editability for nested editable elements"
6:23 PM dandclark: Children inherit editability, but they aren't editing hosts, except if nested one sets contenteditable=false and then enable again in nested nested element
6:24 PM dandclark: So should only editing host get beforeinput when associated EditContext?
6:25 PM dandclark: and nestedly enabling contenteditable should be no-op
6:26 PM johanneswilm: makes sense
6:27 PM johanneswilm: There may be few cases when selection moves to unexpected places
6:29 PM whsieh: what if EditContext is bound to something under editing host?
6:29 PM dandclark: EditContext would do nothing
6:30 PM whsieh: is editing host defined somewhere?
6:32 PM dandclark: we need two kinds of editing hosts. Something where user input does change DOM, but with EditContext there are no DOM changes
6:33 PM dandclark: EditContext spec could clarify this
6:33 PM <dandclark> Dan Clark https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fw3c.github.io%2Fedit-context%2F%23edit-context-differences&data=05%7C01%7Cdaniec%40microsoft.com%7C92296506591648f4c35008db99bd480c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638272810489675174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FJZe0jzJCBwFffPiDgEEJXeK0ryBKl96sx%2F0Xzh%2F46w%3D&reserved=0
6:35 PM <smaug> dandclark: everyone, please review the relevant parts of the spec
6:35 PM johanneswilm: this needs to be clear also on input event side
6:36 PM johanneswilm: I'll take a look at the input events spec
6:36 PM dandclark: EditContext is monkey patching the input events spec
6:40 PM resolution: behavior is defined by the top level editable root
6:41 PM contenteditable=false does still reset editability
6:43 PM dandclark: editing events don't leak out from inner editable areas

I'll make a change to the spec to clarify that these will be the behaviors.

**Comment by dandclark** [comment]
Updated the spec to reflect the resolution: https://github.com/w3c/edit-context/pull/56
