### ISSUE TITLE
`editContext` is on HTMLElement but `attachedElements()` returns Element.

### ISSUE THREAD

**Issue by dandclark** [w3c/edit-context#68]
We got some developer feedback pointing out a minor type inconsistency: the [`editContext`](https://w3c.github.io/edit-context/#dom-htmlelement-editcontext) property is on `HTMLElement`, but [`attachedElements()`](https://w3c.github.io/edit-context/#dom-editcontext-attachedelements) returns `Element`s.

It feels like these should be consistent. `HTMLElement` is clearly the right place for `editContext` since `HTMLElement` also contains `contenteditable` and other editing-related attributes. So if we're going to change one of these it should be to make `attachedElements()` return `sequence<HTMLElement>`.

It does seem very rare for anything to return an `HTMLElement` vs an `Element` so maybe @annevk can advise if there's some convention that would indicate we should keep `sequence<Element>` as the return type.

**Comment by annevk** [comment]
It seems fine to make it more specific. We're generally not super careful about return types as they don't do a whole lot for specification editors.

**Comment by dandclark** [comment]
Minutes from 2023-10-12 Editing WG call:

> 8:39 AM <sanketj_> dandclark: editContext property is on HTMLElement, but editContext property list returns Element.
8:39 AM <sanketj_> dandclark: Proposal is to make them consistent and have editContext property list return HTMLElement.
8:39 AM <sanketj_> Resolution: Accept proposal.
