### ISSUE TITLE
Fix the Status section

### ISSUE THREAD

**Issue by jyasskin** [w3c/edit-context#79]
https://w3c.github.io/edit-context/#sotd says "This document is merely a W3C-internal document. It has no official standing of any kind and does not represent consensus of the W3C Membership.", but the document appears to actually be produced by an official Working Group.

I see that https://github.com/w3c/edit-context/blob/3c4a827cbb5d0d3549e54fd5b5f1db0b638435ea/index.html#L41C15-L41C34 has `group: "webediting"`, but Respec doesn't seem to be applying it correctly.

**Comment by dandclark** [comment]
Seems like this might have been a Respec issue that got fixed. No changes have been made to the spec but the text I now see at https://w3c.github.io/edit-context/#sotd looks correct to me.

> Status of This Document
This section describes the status of this document at the time of its publication. A list of current W3C publications and the latest revision of this technical report can be found in the [W3C technical reports index](https://www.w3.org/TR/) at https://www.w3.org/TR/.

> This document was published by the [Web Editing Working Group](https://www.w3.org/groups/wg/webediting) as an Editor's Draft.
Publication as an Editor's Draft does not imply endorsement by W3C and its Members.
This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.
This document was produced by a group operating under the [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/). W3C maintains a [public list of any patent disclosures](https://www.w3.org/groups/wg/webediting/ipr) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/Consortium/Patent-Policy/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/#sec-Disclosure).
This document is governed by the [12 June 2023 W3C Process Document](https://www.w3.org/2023/Process-20230612/).

**Comment by jyasskin** [comment]
Yep, looks good to me now.
