### ISSUE TITLE
Backspace doesn't delete text in canvas

### ISSUE THREAD

**Issue by ilantc** [w3c/edit-context#93]
Not sure if this is by design or not.

It seems that in order to support deletion of text the user will need to add a keyboard event listener to the canvas element, update his model of the text and update the EditContext with the new text.

Seems like a cumbersome process for a basic input operation.

This reproduces in the https://github.com/w3c/edit-context/blob/gh-pages/canvas_editContext.html demo

**Comment by dandclark** [comment]
Hi @ilantc , can you share the OS and browser version you're seeing this behavior on (found under chrome://version if you're on Edge or Chrome)?

There was a bug along these lines that was fixed back in February so you might be hitting that: https://chromium-review.googlesource.com/c/chromium/src/+/5251988

When things are working correctly, the browser *should* fire a `textupdate` event on the `EditContext` when users do backspace/delete.

**Comment by ilantc** [comment]
Thanks for your reply @dandclark, it did reproduce on chrome 122.0.6261.129 (Official Build) (64-bit) (cohort: Control) 

But it seems to be fixed on edge dev channel (124.0.2450.2 (Official build) dev (64-bit))

Closing this issue
